config/routes.rb
Rails.application.routes.draw do

  root 'users#new'
  resources :users do
    resource  :profile
    resources :posts
    resources :photos
    resources :friends_users, only: [:index]

  end

  namespace :posts do
    concern :commentable
  end

  resources :posts do
    resources :comments
  end

  resources :likes#, only: [:update, :delete]
  resource :session, only: [:new, :create, :destroy]
  resource :friends_users, only: [:create, :destroy]

  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'

  get '/timeline' => 'static_pages#timeline'
  get '/friends' => 'static_pages#friends'
  get '/about' => 'static_pages#about'
  get '/about_edit' => 'static_pages#about_edit'
  get '/photos' => 'static_pages#photos'

end

app/models/friends_user.rb
class FriendsUser < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/controllers/friends_users_controller.rb
class FriendsUsersController < ApplicationController
  # before_action :require_current_user, only: [:create, :destroy]

  def create
    new_friend = User.find(params[:user_id])
    current_user.friends << new_friend
    new_friend.friends << current_user
    redirect_to user_path(new_friend)
  end

  def destroy
    old_friend = User.find(params[:user_id])
    current_user.friends.delete(old_friend)
    old_friend.friends.delete(current_user)
    redirect_to user_path(old_friend)
  end

  def index
    @user = User.find(params[:user_id])
    @friends = @user.friends
  end

end

app/helpers/friends_users_helper.rb
module FriendsUsersHelper
end

app/views/friends_users/index.html.erb
<main class="friends-main">
  <div class="container">
    <!--Header-->
    <div class="friends-header">
      <h1>Friends</h1>
    </div>
    <!--Friends-->
    <div class="friends-container">
      <div class="row">
        <% @friends.each do |friend| %>
          <div class="friend col-xs-12 col-md-6">
            <a class="friend-photo" href="#">
              <img src="assets/user_silhouette_generic.gif">
            </a>
            <div class="friend-info">
              <!-- <a class="friend-name" href="#">Hermione Granger</a> -->
              <%= link_to friend.profile.full_name, user_path(friend), class: "friend-name" %>
              <p class="friend-count">432 Friends</p>
            </div>
            <!-- <a class="btn btn-default unfriend-button" href="#" role="button">Unfriend Me</a> -->
            <%= link_to "Unfriend Me", friends_users_path(user_id: friend.id), method: :delete, class: "btn btn-default unfriend-button" %>
          </div>
        <% end %>
        <!-- <div class="friend col-xs-12 col-md-6">
          <a class="friend-photo" href="#">
            <img src="assets/user_silhouette_generic.gif">
          </a>
          <div class="friend-info">
            <a class="friend-name" href="#">Hermione Granger</a>
            <p class="friend-count">432 Friends</p>
          </div>
          <a class="btn btn-default unfriend-button" href="#" role="button">Unfriend Me</a>
        </div>
      </div>
      <div class="row">
        <div class="friend col-xs-12 col-md-6">
          <a class="friend-photo" href="#">
            <img src="assets/user_silhouette_generic.gif">
          </a>
          <div class="friend-info">
            <a class="friend-name" href="#">Hermione Granger</a>
            <p class="friend-count">432 Friends</p>
          </div>
          <a class="btn btn-default unfriend-button" href="#" role="button">Unfriend Me</a>
        </div>
        <div class="friend col-xs-12 col-md-6">
          <a class="friend-photo" href="#">
            <img src="assets/user_silhouette_generic.gif">
          </a>
          <div class="friend-info">
            <a class="friend-name" href="#">Hermione Granger</a>
            <p class="friend-count">432 Friends</p>
          </div>
          <a class="btn btn-default unfriend-button" href="#" role="button">Unfriend Me</a>
        </div>
      </div>
      <div class="row">
        <div class="friend col-xs-12 col-md-6">
          <a class="friend-photo" href="#">
            <img src="assets/user_silhouette_generic.gif">
          </a>
          <div class="friend-info">
            <a class="friend-name" href="#">Hermione Granger</a>
            <p class="friend-count">432 Friends</p>
          </div>
          <a class="btn btn-default unfriend-button" href="#" role="button">Unfriend Me</a>
        </div>
        <div class="friend col-xs-12 col-md-6">
          <a class="friend-photo" href="#">
            <img src="assets/user_silhouette_generic.gif">
          </a>
          <div class="friend-info">
            <a class="friend-name" href="#">Hermione Granger</a>
            <p class="friend-count">432 Friends</p>
          </div>
          <a class="btn btn-default unfriend-button" href="#" role="button">Unfriend Me</a>
        </div> -->
      </div>
    </div>
  </div>
</main>