config/routes.rb
Rails.application.routes.draw do

  root 'users#new'
  resources :users do
    resource  :profile
    resources :posts
    resources :photos
    resources :friends_users, only: [:index]

  end

  namespace :posts do
    concern :commentable
  end

  resources :posts do
    resources :comments
  end

  resources :likes#, only: [:update, :delete]
  resource :session, only: [:new, :create, :destroy]
  resource :friends_users, only: [:create, :destroy]

  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'

  get '/timeline' => 'static_pages#timeline'
  get '/friends' => 'static_pages#friends'
  get '/about' => 'static_pages#about'
  get '/about_edit' => 'static_pages#about_edit'
  get '/photos' => 'static_pages#photos'

end

app/views/shared/_comment_form.html.erb
<%= simple_form_for [post, @comment] do |f| %>
  <%= f.input :body, placeholder: 'Write a comment...', label: false %>
  <%= f.submit "Comment" %>
<% end %>

app/views/shared/_flash_messages.html.erb
<div id="flash_messages">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, :class => "flash #{key}") %>
  <% end %>
</div>

app/views/shared/_liked_by.erb
<div class="post-interaction">
  <%= signed_in_user_likes(post)  %>
  <%#= who_likes(post).each do |link|  %>
    <%#= link %>
  <%# end %>


  like this
</div>


<!-- TODO pluralize 'like this' -->

app/views/shared/_nav_home.html.erb
<nav class="navbar navbar-default" id="navhome">
  <div class="container">
    <!--Toggle when mobile -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Danebook</a>
    </div>
    <div class="form-group navbar-right">
      <%= form_tag session_path do %>
        <%= label_tag do %>
          Email
          <%= text_field_tag "session[email]", nil, class: "form_text" %>
        <% end %>

        <%= label_tag do %>
          Password
          <%= password_field_tag "session[password]", nil, class: "form_text" %>
        <% end %>

        <%= label_tag do %>
          Remember me?
          <%= check_box_tag :remember_me %>
        <% end %>

        <%= submit_tag "Log in", :html => {class: "btn btn-info"} %>
      <% end %>
      <!-- <table>
        <tr>
          <th>
            <label>Email:</label>
          </th>
          <th>
            <label>Password:</label>
          </th>
        </tr>
        <tr>
            <td>
            <input type="email" class="form-control input-sm" id="email">
          </td>
            <td>
            <input type="password" class="form-control input-sm" id="password">
          </td>
          <td>
            <button type="submit" class="btn btn-info">Log In</button>
          </td>
        </tr>
      </table> -->
    </div>
  </div>
  <!-- Collect form for toggling -->
  <!--<div class="collapse navbar-collapse">-->
  <!--  <ul class="nav navbar-right">-->
  <!--    <form class="navbar-form">-->
  <!--      <div class="form-group">-->
  <!--        <label for="password">Password:</label>-->
  <!--        <input type="text" class="form-control" id="password">-->
  <!--      </div>-->
  <!--      <button type="submit" class="btn btn-info">Log In</button>-->
  <!--    </form>-->
  <!--  </ul>-->
  <!--</div>-->
</nav>

app/views/shared/_nav_home_depricated.html.erb
<nav class="navbar navbar-default" id="navhome">
  <div class="container">
    <!--Toggle when mobile -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Danebook</a>
    </div>
    <div class="form-group navbar-right">
      <%= form_tag session_path do %>
        <%= label_tag do %>
          Email
          <%= text_field_tag "session[email]", nil, class: "form_text" %>
        <% end %>

        <%= label_tag do %>
          Password
          <%= password_field_tag "session[password]", nil, class: "form_text" %>
        <% end %>

        <%= label_tag do %>
          Remember me?
          <%= check_box_tag :remember_me %>
        <% end %>

        <%= submit_tag "Log in", :html => {class: "btn btn-info"} %>
      <% end %>
      <!-- <table>
        <tr>
          <th>
            <label>Email:</label>
          </th>
          <th>
            <label>Password:</label>
          </th>
        </tr>
        <tr>
            <td>
            <input type="email" class="form-control input-sm" id="email">
          </td>
            <td>
            <input type="password" class="form-control input-sm" id="password">
          </td>
          <td>
            <button type="submit" class="btn btn-info">Log In</button>
          </td>
        </tr>
      </table> -->
    </div>
  </div>
  <!-- Collect form for toggling -->
  <!--<div class="collapse navbar-collapse">-->
  <!--  <ul class="nav navbar-right">-->
  <!--    <form class="navbar-form">-->
  <!--      <div class="form-group">-->
  <!--        <label for="password">Password:</label>-->
  <!--        <input type="text" class="form-control" id="password">-->
  <!--      </div>-->
  <!--      <button type="submit" class="btn btn-info">Log In</button>-->
  <!--    </form>-->
  <!--  </ul>-->
  <!--</div>-->
</nav>

app/views/shared/_navbar.html.erb
<!--Navigation Bar-->

<nav class="navbar navbar-fixed-top navbar-main">
  <div class="container">
    <div class="row">
      <div class="col-xs-4 col-md-3">
        <div class="navbar-header">
          <div class="navbar-logo">
            <!--<a href="home.html">--><a href="<%= root_path %>">
              <img alt="denmark flag logo" class="logo" src="assets/danish_flag.gif">
            </a>
          </div>
          <a class="navbar-brand">Danebook</a>
        </div>
      </div>
      <div class="col-xs-6 col-md-7">
        <form class="navbar-user-search" class="form-inline">
          <input type="text" class="form-control" placeholder="Search for Users">
        </form>
      </div>
      <div class="col-xs-2 col-md-2">
        <div class="navbar-current-user">
          <%= link_to current_user.profile.first_name, edit_user_path(current_user) %>
          <%= link_to "Logout", logout_path %>
          <!-- <a href="about.html">Harry</a> -->
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_navbar_home.html.erb
<!--Navigation Bar (Home Page)-->

<nav class="navbar navbar-fixed-top home-navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand">Danebook</a>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#login">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
    </div>
    <!-- <form id="login" class="collapse navbar-collapse">
      <div class="form-group">
        <label for="login-email-input">Email</label>
        <input type="email" class="form-control" id="login-email-input">
      </div>
      <div class="form-group">
        <label for="login-password-input">Password</label>
        <input type="password" class="form-control" id="login-password-input">
      </div>
      <button type="submit" formaction="about.html" class="btn btn-default">Log In</button>
    </form> -->
    <%= form_tag session_path, class: 'login' do %>
      <%= label_tag do %>
        Email
        <%= text_field_tag "session[email]" %>
      <% end %>

      <%= label_tag do %>
        Password
        <%= password_field_tag "session[password]" %>
      <% end %>

      <%= label_tag do %>
        Remember me?
        <%= check_box_tag :remember_me %>
      <% end %>

      <%= submit_tag "Log in" %>
    <% end %>
  </div>
</nav>

app/views/shared/_post_form.html.erb
<%= simple_form_for [current_user, @post] do |f| %>
  <%= f.input :body, placeholder: 'Tell the world something...', label: false %>
  <%= f.submit "post" %>
<% end %>

app/views/shared/_top_section.html.erb
<!--Top Section (Cover & Personal PHotos, Middle Navigation-->

<section class="top-section">
  <div class="container">
    <!--Cover Photo-->
    <div class="cover-photo">
      <img src="assets/hogwarts_small.jpg">
    </div>
    <!--Profile Photo-->
    <div class="personal-photo">
      <%= image_tag @user.profile.avatar.url(:medium) %>
    </div>
    <!--Name-->
    <div class="profile-name">
      <h1>Harry Potter</h1>
    </div>
    <!--Middle Navigation Bar-->
    <nav class="navbar navbar-default navbar-mid">
      <div class="navbar-mid-buttons">
        <div class="navbar-profile-buttons btn-group">
          <%= link_to "Timeline", user_posts_path(@user), class: "btn btn-default", role: "button" %>
          <%= link_to "About", user_path(@user), class: "btn btn-default", role: "button" %>
          <%= link_to "Photos", user_photos_path(@user), class: "btn btn-default", role: "button" %>
          <%= link_to "Friends", user_friends_users_path(@user), class: "btn btn-default", role: "button" %>
<!--           <a class="btn btn-default" href="timeline.html" role="button" disabled="disabled">Timeline</a>
          <a class="btn btn-default" href="about.html" role="button">About</a>
          <a class="btn btn-default" href="photos.html" role="button">Photos (<span id="photo-count">123</span>)</a>
          <a class="btn btn-default" href="friends.html" role="button">Friends (<span id="friend-count">542</span>)</a> -->
        </div>
        <div class="navbar-edit-button">
          <%= edit_or_friend_link %>
          <%#= link_to "Edit Profile", about_edit_path, class: "btn btn-link", role: "button" %>
          <!-- <a class="btn btn-link" href="about_edit.html" role="button">Edit Profile</a> -->
        </div>
      </div>
    </nav>
  </div>
</section>