config/routes.rb
Rails.application.routes.draw do

  root 'users#new'
  resources :users do
    resource  :profile
    resources :posts
    resources :photos
    resources :friends_users, only: [:index]

  end

  namespace :posts do
    concern :commentable
  end

  resources :posts do
    resources :comments
  end

  resources :likes#, only: [:update, :delete]
  resource :session, only: [:new, :create, :destroy]
  resource :friends_users, only: [:create, :destroy]

  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'

  get '/timeline' => 'static_pages#timeline'
  get '/friends' => 'static_pages#friends'
  get '/about' => 'static_pages#about'
  get '/about_edit' => 'static_pages#about_edit'
  get '/photos' => 'static_pages#photos'

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user

  has_attached_file :photo_file, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo_file, content_type: /\Aimage\/.*\z/
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_user, :only => [:show, :edit, :update, :destroy]
  # before_action :require_current_user, only: [:new, :edit, :update, :destroy]

  def index
    @user = User.find(params[:user_id])
    @photos = @user.photos
  end

  def show
  end

  def new
    @user = current_user
    @photo = Photo.new
  end

  def create
    @photo = current_user.photos.build(photo_params)
    if @photo.save
      flash[:success] = "You added a photo"
      redirect_to user_photos_path(current_user)
    else
      flash.now[:error] = "Photo faild to save"
      render user_photos_path(current_user)
    end
  end

  def update
  end

  private

    def photo_params
      params.require(:photo).permit(:photo_file)

    end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/index.html.erb
<!--Main Content - Photos-->
<main class="photos-main">
  <div class="container">
    <!--Header-->
    <div class="photos-header">
      <h1>Photos</h1>
      <!-- <a class="btn btn-primary" href="#" role="button">Add Photo!</a> -->
      <%= link_to "Add Photo!", new_user_photo_path(current_user), class: "btn btn-primary", role: "button" %>
    </div>
    <!--Photos-->
    <div class="photos-container">
      <% @photos.each do |photo| %>
        <div class="row">
          <div class="photo col-xs-6 col-sm-3">
            <a href="#">
              <!-- <img src="assets/icon_photo_small.png"> -->
              <%= image_tag photo.photo_file.url %>
            </a>
            <p class="photo-date">Uploaded January 1, 2015</p>
            
          </div>
          <div class="photo col-xs-6 col-sm-3">
            <a href="#">
              <img src="assets/icon_photo_small.png">
            </a>
            <p class="photo-date">Uploaded January 1, 2015</p>
          </div>
          <div class="photo col-xs-6 col-sm-3">
            <a href="#">
              <img src="assets/icon_photo_small.png">
            </a>
            <p class="photo-date">Uploaded January 1, 2015</p>
          </div>
          <div class="photo col-xs-6 col-sm-3">
            <a href="#">
              <img src="assets/icon_photo_small.png">
            </a>
            <p class="photo-date">Uploaded January 1, 2015</p>
          </div>
        </div>
      <% end %>
      <div class="row">
        <div class="photo col-xs-6 col-sm-3">
          <a href="#">
            <img src="assets/icon_photo_small.png">
          </a>
          <p class="photo-date">Uploaded January 1, 2015</p>
        </div>
        <div class="photo col-xs-6 col-sm-3">
          <a href="#">
            <img src="assets/icon_photo_small.png">
          </a>
          <p class="photo-date">Uploaded January 1, 2015</p>
        </div>
        <div class="photo col-xs-6 col-sm-3">
          <a href="#">
            <img src="assets/icon_photo_small.png">
          </a>
          <p class="photo-date">Uploaded January 1, 2015</p>
        </div>
        <div class="photo col-xs-6 col-sm-3">
          <a href="#">
            <img src="assets/icon_photo_small.png">
          </a>
          <p class="photo-date">Uploaded January 1, 2015</p>
        </div>
      </div>
      <div class="row">
        <div class="photo col-xs-6 col-sm-3">
          <a href="#">
            <img src="assets/icon_photo_small.png">
          </a>
          <p class="photo-date">Uploaded January 1, 2015</p>
        </div>
        <div class="photo col-xs-6 col-sm-3">
          <a href="#">
            <img src="assets/icon_photo_small.png">
          </a>
          <p class="photo-date">Uploaded January 1, 2015</p>
        </div>
        <div class="photo col-xs-6 col-sm-3">
          <a href="#">
            <img src="assets/icon_photo_small.png">
          </a>
          <p class="photo-date">Uploaded January 1, 2015</p>
        </div>
        <div class="photo col-xs-6 col-sm-3">
          <a href="#">
            <img src="assets/icon_photo_small.png">
          </a>
          <p class="photo-date">Uploaded January 1, 2015</p>
        </div>
      </div>
      <div class="row">
        <div class="photo col-xs-6 col-sm-3">
          <a href="#">
            <img src="assets/icon_photo_small.png">
          </a>
          <p class="photo-date">Uploaded January 1, 2015</p>
        </div>
        <div class="photo col-xs-6 col-sm-3">
          <a href="#">
            <img src="assets/icon_photo_small.png">
          </a>
          <p class="photo-date">Uploaded January 1, 2015</p>
        </div>
        <div class="photo col-xs-6 col-sm-3">
          <a href="#">
            <img src="assets/icon_photo_small.png">
          </a>
          <p class="photo-date">Uploaded January 1, 2015</p>
        </div>
        <div class="photo col-xs-6 col-sm-3">
          <a href="#">
            <img src="assets/icon_photo_small.png">
          </a>
          <p class="photo-date">Uploaded January 1, 2015</p>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/photos/new.html.erb
<h1>Add a photo</h1>
<%= simple_form_for [current_user, @photo], url: user_photos_path do |f|  %>
  <%= f.input :photo_file, as: :file %>
  <%= f.button :submit %>
<% end %>